<?php

use Illuminate\Database\Seeder;

class PostsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $posts = array(
        	['id' => 1, 'subjek'=>'Hati-Hati Penipuan!', 'isi'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse scelerisque tortor id nunc tincidunt volutpat. Mauris cursus libero nec eros blandit, ac lacinia sem tincidunt. Nunc imperdiet tellus et laoreet facilisis. Aliquam in cursus elit. Cras lectus eros, lacinia quis dui eu, euismod viverra neque. Vestibulum dignissim orci eget ligula laoreet, sit amet convallis arcu dignissim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vel pharetra lacus. Vivamus volutpat odio sed vehicula pretium. Nunc sed sagittis massa. Nam felis augue, sagittis et tortor ac, tempus bibendum nibh. Mauris sem elit, tristique in venenatis a, egestas a nisl. Maecenas egestas lectus ac sapien tristique suscipit. Nam egestas nec turpis at tempor. Ut hendrerit rhoncus nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;<br>Nulla enim risus, luctus ac nibh a, sagittis vulputate sapien. Nulla et lacinia augue. Maecenas nisi nunc, iaculis semper vestibulum ut, mattis in lacus. Vestibulum ut feugiat velit. Sed dapibus nibh eget ligula bibendum placerat. Integer pulvinar, dui luctus ultrices mattis, diam eros eleifend quam, et commodo sem turpis ut nibh. Curabitur lacus nibh, imperdiet ac massa nec, varius pellentesque risus. In hac habitasse platea dictumst. Nulla ut diam venenatis, finibus nibh vel, tincidunt justo. In gravida eleifend dui id posuere. Nulla ipsum elit, convallis at tincidunt cursus, mollis sed nibh. Nam facilisis, nulla ut imperdiet euismod, leo ligula luctus sapien, nec tristique enim enim id nunc. Nam vel condimentum nibh. Morbi ac nisl eget mi lobortis eleifend. Vestibulum placerat dolor in tincidunt aliquet.', 'user_id'=>3, 'kategori_id'=>1],
        	['id' => 2, 'subjek'=>'Pengumuman Mata Kuliah Pemrograman Terdistribusi', 'isi'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse scelerisque tortor id nunc tincidunt volutpat. Mauris cursus libero nec eros blandit, ac lacinia sem tincidunt. Nunc imperdiet tellus et laoreet facilisis. Aliquam in cursus elit. Cras lectus eros, lacinia quis dui eu, euismod viverra neque. Vestibulum dignissim orci eget ligula laoreet, sit amet convallis arcu dignissim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vel pharetra lacus. Vivamus volutpat odio sed vehicula pretium. Nunc sed sagittis massa. Nam felis augue, sagittis et tortor ac, tempus bibendum nibh. Mauris sem elit, tristique in venenatis a, egestas a nisl. Maecenas egestas lectus ac sapien tristique suscipit. Nam egestas nec turpis at tempor. Ut hendrerit rhoncus nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;<br>Nulla enim risus, luctus ac nibh a, sagittis vulputate sapien. Nulla et lacinia augue. Maecenas nisi nunc, iaculis semper vestibulum ut, mattis in lacus. Vestibulum ut feugiat velit. Sed dapibus nibh eget ligula bibendum placerat. Integer pulvinar, dui luctus ultrices mattis, diam eros eleifend quam, et commodo sem turpis ut nibh. Curabitur lacus nibh, imperdiet ac massa nec, varius pellentesque risus. In hac habitasse platea dictumst. Nulla ut diam venenatis, finibus nibh vel, tincidunt justo. In gravida eleifend dui id posuere. Nulla ipsum elit, convallis at tincidunt cursus, mollis sed nibh. Nam facilisis, nulla ut imperdiet euismod, leo ligula luctus sapien, nec tristique enim enim id nunc. Nam vel condimentum nibh. Morbi ac nisl eget mi lobortis eleifend. Vestibulum placerat dolor in tincidunt aliquet.', 'user_id'=>3, 'kategori_id'=>2],
        	['id' => 3, 'subjek'=>'Pengumuman Mata Kuliah Kecerdasan Buatan', 'isi'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse scelerisque tortor id nunc tincidunt volutpat. Mauris cursus libero nec eros blandit, ac lacinia sem tincidunt. Nunc imperdiet tellus et laoreet facilisis. Aliquam in cursus elit. Cras lectus eros, lacinia quis dui eu, euismod viverra neque. Vestibulum dignissim orci eget ligula laoreet, sit amet convallis arcu dignissim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vel pharetra lacus. Vivamus volutpat odio sed vehicula pretium. Nunc sed sagittis massa. Nam felis augue, sagittis et tortor ac, tempus bibendum nibh. Mauris sem elit, tristique in venenatis a, egestas a nisl. Maecenas egestas lectus ac sapien tristique suscipit. Nam egestas nec turpis at tempor. Ut hendrerit rhoncus nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;<br>Nulla enim risus, luctus ac nibh a, sagittis vulputate sapien. Nulla et lacinia augue. Maecenas nisi nunc, iaculis semper vestibulum ut, mattis in lacus. Vestibulum ut feugiat velit. Sed dapibus nibh eget ligula bibendum placerat. Integer pulvinar, dui luctus ultrices mattis, diam eros eleifend quam, et commodo sem turpis ut nibh. Curabitur lacus nibh, imperdiet ac massa nec, varius pellentesque risus. In hac habitasse platea dictumst. Nulla ut diam venenatis, finibus nibh vel, tincidunt justo. In gravida eleifend dui id posuere. Nulla ipsum elit, convallis at tincidunt cursus, mollis sed nibh. Nam facilisis, nulla ut imperdiet euismod, leo ligula luctus sapien, nec tristique enim enim id nunc. Nam vel condimentum nibh. Morbi ac nisl eget mi lobortis eleifend. Vestibulum placerat dolor in tincidunt aliquet.', 'user_id'=>3, 'kategori_id'=>2],
        	['id' => 4, 'subjek'=>'Jokes of the Day', 'isi'=>'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse scelerisque tortor id nunc tincidunt volutpat. Mauris cursus libero nec eros blandit, ac lacinia sem tincidunt. Nunc imperdiet tellus et laoreet facilisis. Aliquam in cursus elit. Cras lectus eros, lacinia quis dui eu, euismod viverra neque. Vestibulum dignissim orci eget ligula laoreet, sit amet convallis arcu dignissim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vel pharetra lacus. Vivamus volutpat odio sed vehicula pretium. Nunc sed sagittis massa. Nam felis augue, sagittis et tortor ac, tempus bibendum nibh. Mauris sem elit, tristique in venenatis a, egestas a nisl. Maecenas egestas lectus ac sapien tristique suscipit. Nam egestas nec turpis at tempor. Ut hendrerit rhoncus nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;<br>Nulla enim risus, luctus ac nibh a, sagittis vulputate sapien. Nulla et lacinia augue. Maecenas nisi nunc, iaculis semper vestibulum ut, mattis in lacus. Vestibulum ut feugiat velit. Sed dapibus nibh eget ligula bibendum placerat. Integer pulvinar, dui luctus ultrices mattis, diam eros eleifend quam, et commodo sem turpis ut nibh. Curabitur lacus nibh, imperdiet ac massa nec, varius pellentesque risus. In hac habitasse platea dictumst. Nulla ut diam venenatis, finibus nibh vel, tincidunt justo. In gravida eleifend dui id posuere. Nulla ipsum elit, convallis at tincidunt cursus, mollis sed nibh. Nam facilisis, nulla ut imperdiet euismod, leo ligula luctus sapien, nec tristique enim enim id nunc. Nam vel condimentum nibh. Morbi ac nisl eget mi lobortis eleifend. Vestibulum placerat dolor in tincidunt aliquet.', 'user_id'=>3, 'kategori_id'=>3],);
        DB::table('posts')->insert($posts);
    }
}
